package com.lordnikius.superapp.routine.exercise.step

const val BACK_TWISTS_PREPARATION_STEP_DURATION = 1.0
const val BUTT_AND_BACK_PREPARATION_STEP_DURATION = 1.0
const val CHANGE_TO_BACK_PREPARATION_STEP_DURATION = 1.0
const val HANDS_PREPARATION_STEP_DURATION = 1.0
const val LONGITUDINAL_TWINE_PREPARATION_STEP_DURATION = 1.0
const val QUADS_PREPARATION_STEP_DURATION = 1.0
const val TRANSVERSE_TWINE_PREPARATION_STEP_DURATION = 1.0

const val CHANGE_STEP_SECONDS_DURATION = 1.0
const val RELAX_STEP_SECONDS_HALF_DURATION = 0.5
const val STRETCH_STEP_SECONDS_DURATION = 1.0