package com.lordnikius.superapp.routine.exercise.step

const val BACK_TWISTS_PREPARATION_STEP_DURATION = 15.0
const val BUTT_AND_BACK_PREPARATION_STEP_DURATION = 10.0
const val CHANGE_TO_BACK_PREPARATION_STEP_DURATION = 7.5
const val HANDS_PREPARATION_STEP_DURATION = 10.0
const val LONGITUDINAL_TWINE_PREPARATION_STEP_DURATION = 10.0
const val QUADS_PREPARATION_STEP_DURATION = 10.0
const val TRANSVERSE_TWINE_PREPARATION_STEP_DURATION = 10.0

const val CHANGE_STEP_SECONDS_DURATION = 5.0
const val RELAX_STEP_SECONDS_HALF_DURATION = 5.0
const val STRETCH_STEP_SECONDS_DURATION = 30.0